name: blb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

#--------------- PACKAGES --------------#
dependencies:
  flutter:
    sdk: flutter
  
  

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State management
  get: ^4.6.5

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  flutter_native_splash: ^2.3.2

#------------------ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  #--------------- LOCAL ASSETS --------------------#
  assets:
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/logos/
  
  #---------------- LOCAL FONTS --------------------#